# Generated by Django 5.2 on 2026-06-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reviewed_by',
        ),
    ]
