# Generated by Django 5.2 on 2026-06-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='departure_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='stations.station'),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
